//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIIS.BusinessLogic.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class drpEntities : DbContext
    {
        public drpEntities()
            : base("name=drpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<drp_facility> drp_facility { get; set; }
        public virtual DbSet<drp_gtin> drp_gtin { get; set; }
        public virtual DbSet<drp_gtin_gln_attributes> drp_gtin_gln_attributes { get; set; }
        public virtual DbSet<drp_plan> drp_plan { get; set; }
        public virtual DbSet<drp_sched_demand> drp_sched_demand { get; set; }
        public virtual DbSet<drp_sched_replenish> drp_sched_replenish { get; set; }
    }
}
