//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIIS.BusinessLogic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class drp_gtin_gln_attributes
    {
        public string gtin { get; set; }
        public string gln { get; set; }
        public Nullable<System.DateTime> as_of_date { get; set; }
        public Nullable<double> replenish_pack_qty { get; set; }
        public Nullable<double> safety_stock_qty { get; set; }
        public Nullable<double> planning_daily_demand { get; set; }
        public Nullable<double> on_hand_balance { get; set; }
        public Nullable<double> allocated_balance { get; set; }
        public Nullable<double> on_hold_balance { get; set; }
    }
}
