//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIIS.BusinessLogic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class drp_facility
    {
        public string gln { get; set; }
        public string gln_description { get; set; }
        public Nullable<int> gln_type { get; set; }
        public Nullable<double> gln_capacity_litres { get; set; }
        public string gln_parent { get; set; }
        public Nullable<int> planning_transfer_time_days { get; set; }
        public Nullable<int> planning_replenish_cycle_days { get; set; }
        public Nullable<System.DateTime> planning_next_replenishment { get; set; }
        public Nullable<int> gln_lowcode { get; set; }
    }
}
